// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pb/user/users.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
	rfqs "github.com/mbizmarket/dmp/radiance/proto/pb/rfqs"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Users struct {
	ID                   int64                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CompanyID            int64                `protobuf:"varint,2,opt,name=CompanyID,proto3" json:"CompanyID,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string               `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	VerifiedEmail        int32                `protobuf:"varint,5,opt,name=VerifiedEmail,proto3" json:"VerifiedEmail,omitempty"`
	Status               string               `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Name                 string               `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone                string               `protobuf:"bytes,8,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Mobile               string               `protobuf:"bytes,9,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	JobTitle             string               `protobuf:"bytes,10,opt,name=JobTitle,proto3" json:"JobTitle,omitempty"`
	ImageStorageID       int64                `protobuf:"varint,11,opt,name=ImageStorageID,proto3" json:"ImageStorageID,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=LastLogin,proto3" json:"LastLogin,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	IsNotifPaymentReturn int32                `protobuf:"varint,16,opt,name=IsNotifPaymentReturn,proto3" json:"IsNotifPaymentReturn,omitempty"`
	Campaign             int64                `protobuf:"varint,17,opt,name=Campaign,proto3" json:"Campaign,omitempty"`
	IDToken              string               `protobuf:"bytes,18,opt,name=IDToken,proto3" json:"IDToken,omitempty"`
	LoginInToken         *any.Any             `protobuf:"bytes,19,opt,name=LoginInToken,proto3" json:"LoginInToken,omitempty"`
	Rfqs                 []*rfqs.Rfqs         `protobuf:"bytes,20,rep,name=Rfqs,proto3" json:"Rfqs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb98ca516feadaca, []int{0}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Users) GetCompanyID() int64 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func (m *Users) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Users) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Users) GetVerifiedEmail() int32 {
	if m != nil {
		return m.VerifiedEmail
	}
	return 0
}

func (m *Users) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Users) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Users) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Users) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Users) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *Users) GetImageStorageID() int64 {
	if m != nil {
		return m.ImageStorageID
	}
	return 0
}

func (m *Users) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *Users) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Users) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Users) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Users) GetIsNotifPaymentReturn() int32 {
	if m != nil {
		return m.IsNotifPaymentReturn
	}
	return 0
}

func (m *Users) GetCampaign() int64 {
	if m != nil {
		return m.Campaign
	}
	return 0
}

func (m *Users) GetIDToken() string {
	if m != nil {
		return m.IDToken
	}
	return ""
}

func (m *Users) GetLoginInToken() *any.Any {
	if m != nil {
		return m.LoginInToken
	}
	return nil
}

func (m *Users) GetRfqs() []*rfqs.Rfqs {
	if m != nil {
		return m.Rfqs
	}
	return nil
}

type RespUserData struct {
	Data                 []*Users `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespUserData) Reset()         { *m = RespUserData{} }
func (m *RespUserData) String() string { return proto.CompactTextString(m) }
func (*RespUserData) ProtoMessage()    {}
func (*RespUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb98ca516feadaca, []int{1}
}

func (m *RespUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespUserData.Unmarshal(m, b)
}
func (m *RespUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespUserData.Marshal(b, m, deterministic)
}
func (m *RespUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespUserData.Merge(m, src)
}
func (m *RespUserData) XXX_Size() int {
	return xxx_messageInfo_RespUserData.Size(m)
}
func (m *RespUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_RespUserData.DiscardUnknown(m)
}

var xxx_messageInfo_RespUserData proto.InternalMessageInfo

func (m *RespUserData) GetData() []*Users {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Users)(nil), "user.Users")
	proto.RegisterType((*RespUserData)(nil), "user.RespUserData")
}

func init() { proto.RegisterFile("proto/pb/user/users.proto", fileDescriptor_cb98ca516feadaca) }

var fileDescriptor_cb98ca516feadaca = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x6f, 0x6b, 0xda, 0x40,
	0x18, 0x5f, 0xfc, 0xd7, 0x7a, 0x5a, 0xd7, 0xdd, 0xa4, 0x5c, 0xb3, 0xb1, 0x8a, 0x8c, 0x21, 0x0c,
	0x22, 0xb8, 0x37, 0x85, 0xbd, 0x12, 0x53, 0x4a, 0x46, 0x27, 0x12, 0xed, 0xde, 0x9f, 0xf5, 0x31,
	0x0b, 0x4b, 0xee, 0x62, 0xee, 0xdc, 0x10, 0xf6, 0x3d, 0xf7, 0x75, 0xc6, 0x3d, 0x67, 0xd2, 0xd5,
	0x0e, 0x7c, 0x13, 0xf3, 0xfb, 0x77, 0xf9, 0xf9, 0xdc, 0x1d, 0xb9, 0xcc, 0x72, 0xa9, 0xe5, 0x30,
	0x5b, 0x0e, 0xb7, 0x0a, 0x72, 0x7c, 0x28, 0x0f, 0x39, 0x5a, 0x33, 0xc0, 0xbd, 0x8a, 0xa4, 0x8c,
	0x12, 0x18, 0x22, 0xb7, 0xdc, 0xae, 0x87, 0x3a, 0x4e, 0x41, 0x69, 0x9e, 0x66, 0xd6, 0xe6, 0x5e,
	0x1e, 0x1a, 0xb8, 0xd8, 0xed, 0xa5, 0x37, 0x87, 0x12, 0xa4, 0x99, 0x2e, 0x44, 0x56, 0x7e, 0x39,
	0x5f, 0x6f, 0x14, 0x3e, 0xac, 0xd2, 0xff, 0x53, 0x27, 0xf5, 0x7b, 0x53, 0x84, 0x76, 0x48, 0x25,
	0xf0, 0x99, 0xd3, 0x73, 0x06, 0xd5, 0xb0, 0x12, 0xf8, 0xf4, 0x2d, 0x69, 0x4e, 0x64, 0x9a, 0x71,
	0xb1, 0x0b, 0x7c, 0x56, 0x41, 0xfa, 0x91, 0xa0, 0x5d, 0x52, 0xbf, 0x49, 0x79, 0x9c, 0xb0, 0x6a,
	0xcf, 0x19, 0x34, 0x43, 0x0b, 0xa8, 0x4b, 0x4e, 0x67, 0x5c, 0xa9, 0x5f, 0x32, 0x5f, 0xb1, 0x1a,
	0x0a, 0x25, 0xa6, 0xef, 0xc9, 0xd9, 0x37, 0xc8, 0xe3, 0x75, 0x0c, 0x2b, 0x9b, 0xac, 0xf7, 0x9c,
	0x41, 0x3d, 0x7c, 0x4a, 0xd2, 0x0b, 0xd2, 0x98, 0x6b, 0xae, 0xb7, 0x8a, 0x35, 0x30, 0xbf, 0x47,
	0x94, 0x92, 0xda, 0x94, 0xa7, 0xc0, 0x4e, 0x90, 0xc5, 0x77, 0xd3, 0x61, 0xf6, 0x5d, 0x0a, 0x60,
	0xa7, 0xb6, 0x03, 0x02, 0xb3, 0xc2, 0x57, 0xb9, 0x8c, 0x13, 0x60, 0x4d, 0xbb, 0x82, 0x45, 0xa6,
	0xdb, 0x17, 0xb9, 0x5c, 0xc4, 0x3a, 0x01, 0x46, 0x6c, 0xb7, 0x02, 0xd3, 0x0f, 0xa4, 0x13, 0xa4,
	0x3c, 0x82, 0xb9, 0x96, 0x39, 0x8f, 0x20, 0xf0, 0x59, 0x0b, 0xff, 0xf0, 0x01, 0x4b, 0xaf, 0x49,
	0xf3, 0x8e, 0x2b, 0x7d, 0x27, 0xa3, 0x58, 0xb0, 0x76, 0xcf, 0x19, 0xb4, 0x46, 0xae, 0x67, 0x07,
	0xef, 0x15, 0x83, 0xf7, 0x16, 0xc5, 0xa6, 0x85, 0x8f, 0x66, 0x93, 0x9c, 0xe4, 0xc0, 0x35, 0xac,
	0xc6, 0x9a, 0x9d, 0x1d, 0x4f, 0x96, 0x66, 0x93, 0xbc, 0xcf, 0x56, 0xfb, 0x64, 0xe7, 0x78, 0xb2,
	0x34, 0x9b, 0xa4, 0x0f, 0x09, 0xd8, 0xe4, 0xcb, 0xe3, 0xc9, 0xd2, 0x4c, 0x47, 0xa4, 0x1b, 0xa8,
	0xa9, 0xd4, 0xf1, 0x7a, 0xc6, 0x77, 0x29, 0x08, 0x1d, 0x82, 0xde, 0xe6, 0x82, 0x9d, 0xe3, 0x96,
	0xfd, 0x57, 0x33, 0xf3, 0x9d, 0xf0, 0x34, 0xe3, 0x71, 0x24, 0xd8, 0x2b, 0x9c, 0x5e, 0x89, 0x29,
	0x23, 0x27, 0x81, 0xbf, 0x90, 0x3f, 0x40, 0x30, 0x8a, 0xa3, 0x2f, 0x20, 0xbd, 0x26, 0x6d, 0x1c,
	0x50, 0x20, 0xac, 0xfc, 0x1a, 0x6b, 0x76, 0x9f, 0xd5, 0x1c, 0x8b, 0x5d, 0xf8, 0xc4, 0x49, 0xdf,
	0x91, 0x5a, 0xb8, 0xde, 0x28, 0xd6, 0xed, 0x55, 0x07, 0xad, 0x11, 0xf1, 0xf0, 0x50, 0x1b, 0x26,
	0x44, 0xbe, 0x3f, 0x24, 0xed, 0x10, 0x54, 0x66, 0x0e, 0xb7, 0xcf, 0x35, 0xa7, 0x57, 0xa4, 0x66,
	0x7e, 0x99, 0x83, 0xfe, 0x96, 0x67, 0x6e, 0x9c, 0x87, 0x47, 0x3f, 0x44, 0x61, 0xf4, 0x9b, 0x9c,
	0x87, 0x7c, 0x15, 0x73, 0xf1, 0x00, 0x73, 0xc8, 0x7f, 0xc6, 0x0f, 0xa0, 0xe8, 0x67, 0xd2, 0xba,
	0x05, 0x3d, 0x4e, 0x12, 0x7b, 0x47, 0x2e, 0x9e, 0xf5, 0xba, 0x31, 0xb7, 0xcc, 0xa5, 0x76, 0xb5,
	0x7f, 0xbf, 0xd7, 0x7f, 0x41, 0x3f, 0x92, 0xf6, 0x2d, 0x68, 0x43, 0x4c, 0x4d, 0x23, 0xda, 0xdc,
	0x77, 0x84, 0x8d, 0xdb, 0x29, 0x5e, 0x55, 0x66, 0xcd, 0xcb, 0x06, 0x2e, 0xf9, 0xe9, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x2e, 0x18, 0x56, 0x7b, 0x25, 0x04, 0x00, 0x00,
}
