// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/users/pb/users.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Users struct {
	ID                     int64                     `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CompanyID              int64                     `protobuf:"varint,2,opt,name=CompanyID,proto3" json:"CompanyID,omitempty"`
	Email                  string                    `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password               string                    `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	VerifiedEmail          int32                     `protobuf:"varint,5,opt,name=VerifiedEmail,proto3" json:"VerifiedEmail,omitempty"`
	Status                 string                    `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Name                   string                    `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone                  string                    `protobuf:"bytes,8,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Mobile                 string                    `protobuf:"bytes,9,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	JobTitle               string                    `protobuf:"bytes,10,opt,name=JobTitle,proto3" json:"JobTitle,omitempty"`
	ImageStorageID         int64                     `protobuf:"varint,11,opt,name=ImageStorageID,proto3" json:"ImageStorageID,omitempty"`
	LastLogin              *timestamp.Timestamp      `protobuf:"bytes,12,opt,name=LastLogin,proto3" json:"LastLogin,omitempty"`
	CreatedAt              *timestamp.Timestamp      `protobuf:"bytes,13,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt              *timestamp.Timestamp      `protobuf:"bytes,14,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt              *timestamp.Timestamp      `protobuf:"bytes,15,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	IsNotifPaymentReturn   int32                     `protobuf:"varint,16,opt,name=IsNotifPaymentReturn,proto3" json:"IsNotifPaymentReturn,omitempty"`
	Campaign               int64                     `protobuf:"varint,17,opt,name=Campaign,proto3" json:"Campaign,omitempty"`
	IDToken                string                    `protobuf:"bytes,18,opt,name=IDToken,proto3" json:"IDToken,omitempty"`
	LoginInToken           *any.Any                  `protobuf:"bytes,19,opt,name=LoginInToken,proto3" json:"LoginInToken,omitempty"`
	StorageData            []*StorageData            `protobuf:"bytes,20,rep,name=StorageData,proto3" json:"StorageData,omitempty"`
	RequestorData          *RequestorData            `protobuf:"bytes,21,opt,name=RequestorData,proto3" json:"RequestorData,omitempty"`
	DepartmentApproverData []*DepartmentApproverData `protobuf:"bytes,22,rep,name=DepartmentApproverData,proto3" json:"DepartmentApproverData,omitempty"`
	CategoryApproverData   []*CategoryApproverData   `protobuf:"bytes,23,rep,name=CategoryApproverData,proto3" json:"CategoryApproverData,omitempty"`
	EprocData              *EprocData                `protobuf:"bytes,24,opt,name=EprocData,proto3" json:"EprocData,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                  `json:"-"`
	XXX_unrecognized       []byte                    `json:"-"`
	XXX_sizecache          int32                     `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_80d3bdf6d4de84bd, []int{0}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Users) GetCompanyID() int64 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func (m *Users) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Users) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Users) GetVerifiedEmail() int32 {
	if m != nil {
		return m.VerifiedEmail
	}
	return 0
}

func (m *Users) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Users) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Users) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Users) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Users) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *Users) GetImageStorageID() int64 {
	if m != nil {
		return m.ImageStorageID
	}
	return 0
}

func (m *Users) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *Users) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Users) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Users) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Users) GetIsNotifPaymentReturn() int32 {
	if m != nil {
		return m.IsNotifPaymentReturn
	}
	return 0
}

func (m *Users) GetCampaign() int64 {
	if m != nil {
		return m.Campaign
	}
	return 0
}

func (m *Users) GetIDToken() string {
	if m != nil {
		return m.IDToken
	}
	return ""
}

func (m *Users) GetLoginInToken() *any.Any {
	if m != nil {
		return m.LoginInToken
	}
	return nil
}

func (m *Users) GetStorageData() []*StorageData {
	if m != nil {
		return m.StorageData
	}
	return nil
}

func (m *Users) GetRequestorData() *RequestorData {
	if m != nil {
		return m.RequestorData
	}
	return nil
}

func (m *Users) GetDepartmentApproverData() []*DepartmentApproverData {
	if m != nil {
		return m.DepartmentApproverData
	}
	return nil
}

func (m *Users) GetCategoryApproverData() []*CategoryApproverData {
	if m != nil {
		return m.CategoryApproverData
	}
	return nil
}

func (m *Users) GetEprocData() *EprocData {
	if m != nil {
		return m.EprocData
	}
	return nil
}

type StorageData struct {
	Size                 string   `protobuf:"bytes,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageData) Reset()         { *m = StorageData{} }
func (m *StorageData) String() string { return proto.CompactTextString(m) }
func (*StorageData) ProtoMessage()    {}
func (*StorageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_80d3bdf6d4de84bd, []int{1}
}

func (m *StorageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageData.Unmarshal(m, b)
}
func (m *StorageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageData.Marshal(b, m, deterministic)
}
func (m *StorageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageData.Merge(m, src)
}
func (m *StorageData) XXX_Size() int {
	return xxx_messageInfo_StorageData.Size(m)
}
func (m *StorageData) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageData.DiscardUnknown(m)
}

var xxx_messageInfo_StorageData proto.InternalMessageInfo

func (m *StorageData) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *StorageData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StorageData) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type RequestorData struct {
	ApproverID           int64    `protobuf:"varint,1,opt,name=ApproverID,proto3" json:"ApproverID,omitempty"`
	CompanyID            int64    `protobuf:"varint,2,opt,name=CompanyID,proto3" json:"CompanyID,omitempty"`
	UserID               int64    `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	DepartmentID         int64    `protobuf:"varint,4,opt,name=DepartmentID,proto3" json:"DepartmentID,omitempty"`
	Status               int64    `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestorData) Reset()         { *m = RequestorData{} }
func (m *RequestorData) String() string { return proto.CompactTextString(m) }
func (*RequestorData) ProtoMessage()    {}
func (*RequestorData) Descriptor() ([]byte, []int) {
	return fileDescriptor_80d3bdf6d4de84bd, []int{2}
}

func (m *RequestorData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestorData.Unmarshal(m, b)
}
func (m *RequestorData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestorData.Marshal(b, m, deterministic)
}
func (m *RequestorData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestorData.Merge(m, src)
}
func (m *RequestorData) XXX_Size() int {
	return xxx_messageInfo_RequestorData.Size(m)
}
func (m *RequestorData) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestorData.DiscardUnknown(m)
}

var xxx_messageInfo_RequestorData proto.InternalMessageInfo

func (m *RequestorData) GetApproverID() int64 {
	if m != nil {
		return m.ApproverID
	}
	return 0
}

func (m *RequestorData) GetCompanyID() int64 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func (m *RequestorData) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *RequestorData) GetDepartmentID() int64 {
	if m != nil {
		return m.DepartmentID
	}
	return 0
}

func (m *RequestorData) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type DepartmentApproverData struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ApproverID           int64    `protobuf:"varint,2,opt,name=ApproverID,proto3" json:"ApproverID,omitempty"`
	CompanyID            int64    `protobuf:"varint,3,opt,name=CompanyID,proto3" json:"CompanyID,omitempty"`
	UserID               int64    `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	DepartmentID         int64    `protobuf:"varint,5,opt,name=DepartmentID,proto3" json:"DepartmentID,omitempty"`
	MinTransaction       float32  `protobuf:"fixed32,6,opt,name=MinTransaction,proto3" json:"MinTransaction,omitempty"`
	MaxTransaction       float32  `protobuf:"fixed32,7,opt,name=MaxTransaction,proto3" json:"MaxTransaction,omitempty"`
	Level                int32    `protobuf:"varint,8,opt,name=Level,proto3" json:"Level,omitempty"`
	Status               int32    `protobuf:"varint,9,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepartmentApproverData) Reset()         { *m = DepartmentApproverData{} }
func (m *DepartmentApproverData) String() string { return proto.CompactTextString(m) }
func (*DepartmentApproverData) ProtoMessage()    {}
func (*DepartmentApproverData) Descriptor() ([]byte, []int) {
	return fileDescriptor_80d3bdf6d4de84bd, []int{3}
}

func (m *DepartmentApproverData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartmentApproverData.Unmarshal(m, b)
}
func (m *DepartmentApproverData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartmentApproverData.Marshal(b, m, deterministic)
}
func (m *DepartmentApproverData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartmentApproverData.Merge(m, src)
}
func (m *DepartmentApproverData) XXX_Size() int {
	return xxx_messageInfo_DepartmentApproverData.Size(m)
}
func (m *DepartmentApproverData) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartmentApproverData.DiscardUnknown(m)
}

var xxx_messageInfo_DepartmentApproverData proto.InternalMessageInfo

func (m *DepartmentApproverData) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DepartmentApproverData) GetApproverID() int64 {
	if m != nil {
		return m.ApproverID
	}
	return 0
}

func (m *DepartmentApproverData) GetCompanyID() int64 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func (m *DepartmentApproverData) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *DepartmentApproverData) GetDepartmentID() int64 {
	if m != nil {
		return m.DepartmentID
	}
	return 0
}

func (m *DepartmentApproverData) GetMinTransaction() float32 {
	if m != nil {
		return m.MinTransaction
	}
	return 0
}

func (m *DepartmentApproverData) GetMaxTransaction() float32 {
	if m != nil {
		return m.MaxTransaction
	}
	return 0
}

func (m *DepartmentApproverData) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *DepartmentApproverData) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type CategoryApproverData struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ApproverID           int64    `protobuf:"varint,2,opt,name=ApproverID,proto3" json:"ApproverID,omitempty"`
	CompanyID            int64    `protobuf:"varint,3,opt,name=CompanyID,proto3" json:"CompanyID,omitempty"`
	UserID               int64    `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CategoryID           int64    `protobuf:"varint,5,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	Status               int32    `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryApproverData) Reset()         { *m = CategoryApproverData{} }
func (m *CategoryApproverData) String() string { return proto.CompactTextString(m) }
func (*CategoryApproverData) ProtoMessage()    {}
func (*CategoryApproverData) Descriptor() ([]byte, []int) {
	return fileDescriptor_80d3bdf6d4de84bd, []int{4}
}

func (m *CategoryApproverData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryApproverData.Unmarshal(m, b)
}
func (m *CategoryApproverData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryApproverData.Marshal(b, m, deterministic)
}
func (m *CategoryApproverData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryApproverData.Merge(m, src)
}
func (m *CategoryApproverData) XXX_Size() int {
	return xxx_messageInfo_CategoryApproverData.Size(m)
}
func (m *CategoryApproverData) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryApproverData.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryApproverData proto.InternalMessageInfo

func (m *CategoryApproverData) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *CategoryApproverData) GetApproverID() int64 {
	if m != nil {
		return m.ApproverID
	}
	return 0
}

func (m *CategoryApproverData) GetCompanyID() int64 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func (m *CategoryApproverData) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CategoryApproverData) GetCategoryID() int64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *CategoryApproverData) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type EprocData struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ApproverID           int64    `protobuf:"varint,2,opt,name=ApproverID,proto3" json:"ApproverID,omitempty"`
	CompanyID            int64    `protobuf:"varint,3,opt,name=CompanyID,proto3" json:"CompanyID,omitempty"`
	UserID               int64    `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=Level,proto3" json:"Level,omitempty"`
	Status               int32    `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EprocData) Reset()         { *m = EprocData{} }
func (m *EprocData) String() string { return proto.CompactTextString(m) }
func (*EprocData) ProtoMessage()    {}
func (*EprocData) Descriptor() ([]byte, []int) {
	return fileDescriptor_80d3bdf6d4de84bd, []int{5}
}

func (m *EprocData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EprocData.Unmarshal(m, b)
}
func (m *EprocData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EprocData.Marshal(b, m, deterministic)
}
func (m *EprocData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EprocData.Merge(m, src)
}
func (m *EprocData) XXX_Size() int {
	return xxx_messageInfo_EprocData.Size(m)
}
func (m *EprocData) XXX_DiscardUnknown() {
	xxx_messageInfo_EprocData.DiscardUnknown(m)
}

var xxx_messageInfo_EprocData proto.InternalMessageInfo

func (m *EprocData) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *EprocData) GetApproverID() int64 {
	if m != nil {
		return m.ApproverID
	}
	return 0
}

func (m *EprocData) GetCompanyID() int64 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func (m *EprocData) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *EprocData) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *EprocData) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type RespUserData struct {
	Data                 []*Users `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespUserData) Reset()         { *m = RespUserData{} }
func (m *RespUserData) String() string { return proto.CompactTextString(m) }
func (*RespUserData) ProtoMessage()    {}
func (*RespUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_80d3bdf6d4de84bd, []int{6}
}

func (m *RespUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespUserData.Unmarshal(m, b)
}
func (m *RespUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespUserData.Marshal(b, m, deterministic)
}
func (m *RespUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespUserData.Merge(m, src)
}
func (m *RespUserData) XXX_Size() int {
	return xxx_messageInfo_RespUserData.Size(m)
}
func (m *RespUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_RespUserData.DiscardUnknown(m)
}

var xxx_messageInfo_RespUserData proto.InternalMessageInfo

func (m *RespUserData) GetData() []*Users {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Users)(nil), "pb.Users")
	proto.RegisterType((*StorageData)(nil), "pb.StorageData")
	proto.RegisterType((*RequestorData)(nil), "pb.RequestorData")
	proto.RegisterType((*DepartmentApproverData)(nil), "pb.DepartmentApproverData")
	proto.RegisterType((*CategoryApproverData)(nil), "pb.CategoryApproverData")
	proto.RegisterType((*EprocData)(nil), "pb.EprocData")
	proto.RegisterType((*RespUserData)(nil), "pb.RespUserData")
}

func init() { proto.RegisterFile("proto/users/pb/users.proto", fileDescriptor_80d3bdf6d4de84bd) }

var fileDescriptor_80d3bdf6d4de84bd = []byte{
	// 795 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x92, 0xe2, 0x44,
	0x14, 0x36, 0x30, 0x19, 0x36, 0xcd, 0xcf, 0xce, 0xb6, 0x88, 0x2d, 0xea, 0x4a, 0x51, 0xd6, 0x16,
	0x55, 0x96, 0x50, 0xe2, 0x85, 0xeb, 0x25, 0x45, 0xa6, 0xac, 0x58, 0xcc, 0x16, 0xd5, 0xb0, 0xde,
	0x37, 0x70, 0x86, 0x4d, 0x99, 0xa4, 0x63, 0xd2, 0x8c, 0xe2, 0xcb, 0xa8, 0xef, 0xe0, 0x93, 0xf9,
	0x04, 0x56, 0x9f, 0x0e, 0x21, 0x61, 0x98, 0xe5, 0x6e, 0xef, 0xfa, 0x7c, 0xe7, 0x7c, 0xa7, 0xbf,
	0x7c, 0x9d, 0x3e, 0x4d, 0xba, 0x71, 0x22, 0x95, 0x1c, 0xed, 0x52, 0x48, 0xd2, 0x51, 0xbc, 0x32,
	0x8b, 0x21, 0x82, 0xb4, 0x12, 0xaf, 0xba, 0x5f, 0x6d, 0xa5, 0xdc, 0x06, 0x30, 0x42, 0x64, 0xb5,
	0xbb, 0x1f, 0x29, 0x3f, 0x84, 0x54, 0x89, 0x30, 0x36, 0x45, 0xdd, 0xcf, 0x4e, 0x0b, 0x44, 0xb4,
	0xcf, 0x52, 0x9f, 0x9f, 0xa6, 0x20, 0x8c, 0x55, 0x96, 0xec, 0xff, 0x57, 0x23, 0xf6, 0x5b, 0xbd,
	0x19, 0x6d, 0x91, 0x8a, 0xe7, 0x32, 0xab, 0x67, 0x0d, 0xaa, 0xbc, 0xe2, 0xb9, 0xf4, 0x0b, 0xe2,
	0x4c, 0x65, 0x18, 0x8b, 0x68, 0xef, 0xb9, 0xac, 0x82, 0xf0, 0x11, 0xa0, 0x6d, 0x62, 0xdf, 0x86,
	0xc2, 0x0f, 0x58, 0xb5, 0x67, 0x0d, 0x1c, 0x6e, 0x02, 0xda, 0x25, 0xcf, 0xe6, 0x22, 0x4d, 0x7f,
	0x97, 0xc9, 0x86, 0x5d, 0x61, 0x22, 0x8f, 0xe9, 0xd7, 0xa4, 0xf9, 0x0b, 0x24, 0xfe, 0xbd, 0x0f,
	0x1b, 0xc3, 0xb4, 0x7b, 0xd6, 0xc0, 0xe6, 0x65, 0x90, 0x76, 0xc8, 0xf5, 0x42, 0x09, 0xb5, 0x4b,
	0xd9, 0x35, 0xf2, 0xb3, 0x88, 0x52, 0x72, 0xf5, 0x46, 0x84, 0xc0, 0x6a, 0x88, 0xe2, 0x5a, 0x6b,
	0x98, 0xbf, 0x93, 0x11, 0xb0, 0x67, 0x46, 0x03, 0x06, 0xba, 0xc3, 0x9d, 0x5c, 0xf9, 0x01, 0x30,
	0xc7, 0x74, 0x30, 0x91, 0xd6, 0xf6, 0xb3, 0x5c, 0x2d, 0x7d, 0x15, 0x00, 0x23, 0x46, 0xdb, 0x21,
	0xa6, 0xaf, 0x48, 0xcb, 0x0b, 0xc5, 0x16, 0x16, 0x4a, 0x26, 0x62, 0x0b, 0x9e, 0xcb, 0xea, 0xf8,
	0xc1, 0x27, 0x28, 0x7d, 0x4d, 0x9c, 0x99, 0x48, 0xd5, 0x4c, 0x6e, 0xfd, 0x88, 0x35, 0x7a, 0xd6,
	0xa0, 0x3e, 0xee, 0x0e, 0x8d, 0xbd, 0xc3, 0x83, 0xbd, 0xc3, 0xe5, 0xe1, 0x68, 0xf8, 0xb1, 0x58,
	0x33, 0xa7, 0x09, 0x08, 0x05, 0x9b, 0x89, 0x62, 0xcd, 0xcb, 0xcc, 0xbc, 0x58, 0x33, 0xdf, 0xc6,
	0x9b, 0x8c, 0xd9, 0xba, 0xcc, 0xcc, 0x8b, 0x35, 0xd3, 0x85, 0x00, 0x0c, 0xf3, 0xf9, 0x65, 0x66,
	0x5e, 0x4c, 0xc7, 0xa4, 0xed, 0xa5, 0x6f, 0xa4, 0xf2, 0xef, 0xe7, 0x62, 0x1f, 0x42, 0xa4, 0x38,
	0xa8, 0x5d, 0x12, 0xb1, 0x1b, 0x3c, 0xb2, 0xb3, 0x39, 0xed, 0xef, 0x54, 0x84, 0xb1, 0xf0, 0xb7,
	0x11, 0x7b, 0x81, 0xee, 0xe5, 0x31, 0x65, 0xa4, 0xe6, 0xb9, 0x4b, 0xf9, 0x2b, 0x44, 0x8c, 0xa2,
	0xf5, 0x87, 0x90, 0xbe, 0x26, 0x0d, 0x34, 0xc8, 0x8b, 0x4c, 0xfa, 0x63, 0x94, 0xd9, 0x7e, 0x24,
	0x73, 0x12, 0xed, 0x79, 0xa9, 0x92, 0x7e, 0x47, 0xea, 0xd9, 0xc1, 0xb8, 0x42, 0x09, 0xd6, 0xee,
	0x55, 0x07, 0xf5, 0xf1, 0xf3, 0x61, 0xbc, 0x1a, 0x16, 0x60, 0x5e, 0xac, 0xa1, 0x3f, 0x90, 0x26,
	0x87, 0xdf, 0x76, 0x90, 0x2a, 0x99, 0x20, 0xe9, 0x13, 0xdc, 0xed, 0x85, 0x26, 0x95, 0x12, 0xbc,
	0x5c, 0x47, 0x39, 0xe9, 0xb8, 0x10, 0x8b, 0x44, 0xe9, 0xef, 0x9d, 0xc4, 0x71, 0x22, 0x1f, 0xc0,
	0x74, 0xe8, 0xe0, 0xb6, 0x5d, 0xdd, 0xe1, 0x7c, 0x05, 0x7f, 0x82, 0x49, 0x67, 0xa4, 0x3d, 0x15,
	0x0a, 0xb6, 0x32, 0xd9, 0x97, 0x3a, 0x7e, 0x8a, 0x1d, 0x99, 0xee, 0x78, 0x2e, 0xcf, 0xcf, 0xb2,
	0xe8, 0x37, 0xc4, 0xb9, 0x8d, 0x13, 0xb9, 0xc6, 0x16, 0x0c, 0x3f, 0xab, 0xa9, 0x5b, 0xe4, 0x20,
	0x3f, 0xe6, 0xfb, 0x5e, 0xc9, 0x3a, 0x7d, 0xb7, 0x16, 0xfe, 0x9f, 0x80, 0x77, 0xdf, 0xe1, 0xb8,
	0xd6, 0xd8, 0x72, 0x1f, 0x03, 0x5e, 0x7c, 0x87, 0xe3, 0x5a, 0x63, 0x73, 0xa1, 0xde, 0x65, 0x57,
	0x1e, 0xd7, 0xfd, 0x7f, 0xac, 0x13, 0x4f, 0xe9, 0x4b, 0x42, 0x0e, 0xca, 0xf2, 0x79, 0x52, 0x40,
	0x2e, 0xcc, 0x95, 0x0e, 0xb9, 0xd6, 0xe3, 0xc8, 0x73, 0x71, 0x97, 0x2a, 0xcf, 0x22, 0xda, 0x27,
	0x8d, 0xa3, 0x8f, 0x9e, 0x8b, 0xd3, 0xa5, 0xca, 0x4b, 0x58, 0x61, 0x76, 0xd8, 0x86, 0x6b, 0xa2,
	0xfe, 0xdf, 0x95, 0xa7, 0x8e, 0xef, 0xd1, 0xd0, 0x2b, 0x8b, 0xaf, 0xbc, 0x5f, 0x7c, 0xf5, 0x69,
	0xf1, 0x57, 0xef, 0x15, 0x6f, 0x9f, 0x11, 0xff, 0x8a, 0xb4, 0xee, 0xfc, 0x68, 0x99, 0x88, 0x28,
	0x15, 0x6b, 0xe5, 0xcb, 0x08, 0x07, 0x60, 0x85, 0x9f, 0xa0, 0x58, 0x27, 0xfe, 0x28, 0xd6, 0xd5,
	0xb2, 0xba, 0x12, 0xaa, 0x87, 0xe3, 0x0c, 0x1e, 0x20, 0xc0, 0xe1, 0x68, 0x73, 0x13, 0x14, 0x2c,
	0x72, 0x10, 0x3e, 0x58, 0xf4, 0xaf, 0x75, 0xfe, 0x6f, 0xfc, 0x40, 0x06, 0xbd, 0x24, 0xe4, 0xb0,
	0x7b, 0x6e, 0x4f, 0x01, 0x39, 0x79, 0x15, 0x8e, 0xb2, 0xff, 0xb2, 0x0a, 0xbf, 0xfd, 0x07, 0xd2,
	0x9a, 0x1b, 0x6b, 0x9f, 0x37, 0xb6, 0xac, 0xf0, 0x5b, 0xd2, 0xe0, 0x90, 0xc6, 0x9a, 0x8b, 0x1a,
	0xbf, 0x24, 0x57, 0x78, 0x45, 0x2d, 0xbc, 0xe5, 0x8e, 0xbe, 0xa2, 0xf8, 0xfc, 0x72, 0x84, 0xc7,
	0x77, 0xe4, 0x86, 0x8b, 0x8d, 0x2f, 0xa2, 0x35, 0x2c, 0x20, 0x79, 0xf0, 0xd7, 0x90, 0xd2, 0x1f,
	0x49, 0xfd, 0x27, 0x50, 0x93, 0x20, 0x30, 0xef, 0x74, 0xe7, 0xd1, 0x6c, 0xbc, 0xd5, 0xef, 0x79,
	0xf7, 0xc6, 0x4c, 0xb1, 0xe3, 0x5e, 0xfd, 0x8f, 0x56, 0xd7, 0x58, 0xf3, 0xfd, 0xff, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x9f, 0xa0, 0x3b, 0xa9, 0x5f, 0x08, 0x00, 0x00,
}
